export const FOOD_SWAPS: Record<string, string[]> = {
  "Ice cream": [
    "Apple with a little peanut butter",
    "Protein shake with a few berries",
    "Celery with almond butter",
    "Frozen banana, blended",
  ],
  Cheese: [
    "Cottage cheese with pepper",
    "Part-skim string cheese",
    "Nutritional yeast on vegetables",
    "A few slices of extra-sharp cheddar, slowly",
  ],
  Desserts: [
    "Greek yogurt with berries",
    "One square of dark chocolate",
    "Baked apple with cinnamon",
    "Protein brownie bite",
  ],
  Bread: [
    "Lettuce wrap",
    "High-protein tortilla",
    "Cloud bread",
    "Cucumber rounds",
  ],
  "Oversized portions": [
    "Use a salad plate",
    "Protein first, then pause",
    "Box half before you start",
    "Eat, wait ten minutes, decide again",
  ],
};

export const FOOD_SWAP_TAGS: Record<string, string[]> = {
  "Apple with a little peanut butter": ["peanuts", "nuts"],
  "Protein shake with a few berries": ["dairy"],
  "Celery with almond butter": ["nuts"],
  "Frozen banana, blended": [],
  "Cottage cheese with pepper": ["dairy"],
  "Part-skim string cheese": ["dairy"],
  "Nutritional yeast on vegetables": [],
  "A few slices of extra-sharp cheddar, slowly": ["dairy"],
  "Greek yogurt with berries": ["dairy"],
  "One square of dark chocolate": [],
  "Baked apple with cinnamon": [],
  "Protein brownie bite": ["dairy", "eggs"],
  "Lettuce wrap": [],
  "High-protein tortilla": ["gluten"],
  "Cloud bread": ["eggs", "dairy"],
  "Cucumber rounds": [],
  "Use a salad plate": [],
  "Protein first, then pause": [],
  "Box half before you start": [],
  "Eat, wait ten minutes, decide again": [],
};
